### PR TITLE
Asn1 safety and portability

### PR DESCRIPTION
**Pull request by drbild**
This series improves portability and safety of the asn1 utility functions.

- Exports the certificate length macros as functions for use by wrapper libraries
- Explicitly validates the length of the output buffers for x509 and ASN1 encodings.

### CODE REVIEW

**Comment by zanebeckwith** [comment]
Added one commit to reflect these changes in the `xtt_client`.

Otherwise, LGTM

Good idea

**Comment by drbild** [comment]
@zanebeckwith Nice - I guess my default cmake options didn't build the example programs.

Could you `rebase` that fix into the second commit before merging.  That's a mistake in my second commit --- no sense preserving that in the history.

**Comment by zanebeckwith** [comment]
Done.

Merging...

**Comment by drbild** [comment]
:+1:

**Pull request merged**
