### PR TITLE
Simplify use tpm defines

### PR DESCRIPTION
**Pull request by drbild**
Using the `USE_TPM_DEFINE` template parameter for define the `USE_TPM` macro is unnecessary.  CMake is already configured to define that.  This series removes that macro and converts the affected files from templates to plain headers.

### CODE REVIEW

**Comment by zanebeckwith** [comment]
For reference, this odd structure was introduced in PR #10. That arose in response to an issue we had when the xtt-erlang project tried using system-installed xtt libraries but local headers, I think, which resulted in inconsistent `USE_TPM` defined-ness.

I'm not entirely sure why it was done this odd way, or if we still need to keep this code. I'll have to come back to this.

**Comment by drbild** [comment]
I've added an additional commit that extends the output of `$(pkg-config --cflags xtt)` to include `-DUSE_XTT` iff `xtt` was compiled with TPM support.  For CMake-based users, `xtt-config.cmake` already had this support.

My opinion is that `xtt-erlang` should be fixed to use `pkg-config`, rather than building hacks into this library.

**Comment by drbild** [comment]
xaptum/xtt-erlang#11 adds that pkg-config support, so future XTT releases with this change will not break it.

**Comment by zanebeckwith** [comment]
Good call. Much more elegant. Just wanted to make sure we don't break anything in xtt-erlang.

In that case, LGTM. I'll merge it.

**Pull request merged**
